### ISSUE TITLE
can't compile - missing files

### ISSUE THREAD

**Issue by userdsp** [jackaudio/jack-router#3]
1>------ Build started: Project: JackRouter_MinGW_deps, Configuration: Debug x64 ------
1>combase.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'c:\msys64\opt\asiosdk\common\combase.cpp': No such file or directory
1>dllentry.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'c:\msys64\opt\asiosdk\common\dllentry.cpp': No such file or directory
1>JackRouter.cpp
1>c:\users\dsp\downloads\jack-router-main\jack-router-main\win\jackrouter.h(28): fatal error C1083: Cannot open include file: 'asiosys.h': No such file or directory
1>profport.cpp
1>register.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'c:\msys64\opt\asiosdk\common\register.cpp': No such file or directory
1>Generating Code...
1>Done building project "JackRouter_MinGW_deps.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by userdsp** [comment]
The project file is at complete different location. I never had directory c:\msys64

**Comment by falkTX** [comment]
Project has been reworked with #4 `JackRouter_MinGW_deps.vcxproj` is no longer in the repo.

For msys/mingw we need to re-do things, a makefile is a lot more simple approach.
Will try this myself if I find the time.
