### ISSUE TITLE
Windows README references VC++6, what to do?

### ISSUE THREAD

**Issue by lucianoiam** [jackaudio/jack-router#6]
The win/README still references a Microsoft VC++ 6 project I deleted on 7848654 after adding the modern Visual Studio versions. 

https://github.com/jackaudio/jack-router/blob/6c2e532bb05d2ba59ef210bef2fe270d588c2fdf/win/README#L1

Later this was added which is correct

https://github.com/jackaudio/jack-router/blob/6c2e532bb05d2ba59ef210bef2fe270d588c2fdf/win/README#L7

What do you think should the VC++6 project be brought back, maybe for historic purposes, or that README updated?

The deleted files where:
https://github.com/jackaudio/jack-router/blob/7b671e1af0def3aba535bc504336f5cb7f32b4e7/win/JackRouter.dsp
https://github.com/jackaudio/jack-router/blob/7b671e1af0def3aba535bc504336f5cb7f32b4e7/win/JackRouter.dsw

**Comment by falkTX** [comment]
isnt VC++ 6 like super old?

afaik only windows 10 is the supported OS by MS now, so ignore whatever does not work on win10 anymore.

**Comment by lucianoiam** [comment]
Just checked, 1998 lol. Agree.
